### PR TITLE
Get tx status

### LINKED ISSUE #57: Add support for get_status(txhash)

### PR DESCRIPTION
**Pull request by rllola**
closes #57;

- [x] added method get_status
- [x] jsonrpc test (going to fail because no testnet node available)
- [x] Use configuration file for remote node information
- [x] Proper error code if tx not mined

### CODE REVIEW

**Comment by Schwartz10** [comment]
Hey, i was just peeping through the issues/PRs here, and stumbled upon this one - I noticed your `get_status` method hits `ChainGetMessage` - are you using that as a measure to know when a message has been "confirmed" in the network?

**Comment by rllola** [comment]
> Hey, i was just peeping through the issues/PRs here, and stumbled upon this one - I noticed your `get_status` method hits `ChainGetMessage` - are you using that as a measure to know when a message has been "confirmed" in the network?

Actually no. It does return an error if the message hasn't been validated yet and only when we have a result we know it has been confirmed. It does bother me a bit. We are open to proposition here.

**Comment by Schwartz10** [comment]
I've been talking to why about [StateGetReceipt](https://github.com/filecoin-project/lotus/blob/master/api/api_full.go#L126) for this purpose, but it doesn't seem to be working yet. 

Conversation going on [here](https://filecoinproject.slack.com/archives/GRT37S147/p1583440322084600)

**Comment by rllola** [comment]
> I've been talking to why about [StateGetReceipt](https://github.com/filecoin-project/lotus/blob/master/api/api_full.go#L126) for this purpose, but it doesn't seem to be working yet.
> 
> Conversation going on [here](https://filecoinproject.slack.com/archives/GRT37S147/p1583440322084600)

Nice! Yeah it looks like it is what we need.
I notice there is a lot more call possible in lotus than what they have documented (https://documenter.getpostman.com/view/4872192/SWLh5mUd?version=latest). 

Also could you confirm that ` StateWaitMsg` will return an answer only once the message has been validated ? It keep hanging for me... Not sure if it is my connection or how they do it.

**Comment by jleni** [comment]
Disabled test and open a tracking issue here:
https://github.com/Zondax/filecoin-rs/issues/71

**Pull request merged**
